# Generated by Django 5.1.4 on 2025-05-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='designing_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='is_classic',
            field=models.BooleanField(default=False),
        ),
    ]
