# Generated by Django 5.1.4 on 2025-05-13 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0002_remove_product_gender_remove_product_occasion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jewelleryapp.occasion'),
            preserve_default=False,
        ),
    ]
