# Generated by Django 5.1.4 on 2025-04-21 12:20

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0002_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('karantage', models.CharField(blank=True, max_length=20, null=True)),
                ('material_color', models.CharField(blank=True, max_length=20, null=True)),
                ('pendant_height', models.CharField(blank=True, max_length=20, null=True)),
                ('pandant_width', models.CharField(blank=True, max_length=20, null=True)),
                ('gross_weight', models.CharField(blank=True, max_length=20, null=True)),
                ('diamont_details', models.TextField(blank=True, null=True)),
                ('general_details', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('stone_weight', models.CharField(max_length=50)),
                ('stone_price', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=10)),
                ('making_charge', models.CharField(max_length=10)),
                ('sub_total', models.CharField(max_length=100)),
                ('gst', models.CharField(max_length=10)),
                ('grand_total', models.CharField(max_length=100)),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelleryapp.metal')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelleryapp.stone')),
            ],
        ),
    ]
