# Generated by Django 5.1.4 on 2025-06-26 12:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarcategory',
            name='occasion_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
