# Generated by Django 5.1.4 on 2025-06-11 05:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0002_phoneotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
