# Generated by Django 5.1.4 on 2025-05-17 05:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0003_product_description_product_pendant_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='color_gradient',
            field=models.CharField(default=1, help_text="Enter a color gradient (e.g., 'linear-gradient(to right, #ff7e5f, #feb47b)') for header", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gender',
            name='gif',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='gender',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
