# Generated by Django 5.1.4 on 2025-04-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0003_metal_stone_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
