# Generated by Django 5.1.4 on 2025-06-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0004_productenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productenquiry',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
