# Generated by Django 5.1.4 on 2025-05-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0004_product_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metal',
            name='weight',
        ),
        migrations.AlterField(
            model_name='product',
            name='stone_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
