# Generated by Django 5.1.4 on 2025-05-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0004_gender_color_gradient_gender_gif_gender_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='color_gradient',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='gif',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='title',
        ),
    ]
