# Generated by Django 5.1.4 on 2025-04-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
