# Generated by Django 5.1.4 on 2025-05-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0005_remove_metal_weight_alter_product_stone_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='metal',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
