# Generated by Django 5.1.4 on 2025-05-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0005_remove_gender_color_gradient_remove_gender_gif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
