# Generated by Django 5.1.4 on 2025-06-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0005_alter_productenquiry_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='productenquiry',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
