# Generated by Django 5.1.4 on 2025-04-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0006_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
