# Generated by Django 5.1.4 on 2025-05-13 09:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0006_metal_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metal',
            name='weight',
        ),
        migrations.AddField(
            model_name='metal',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
