# Generated by Django 5.1.4 on 2025-06-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0006_productenquiry_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agree',
            field=models.BooleanField(default=False, help_text='User must agree to privacy policy'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs')], max_length=10, null=True),
        ),
    ]
