# Generated by Django 5.1.4 on 2025-05-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0007_remove_metal_weight_metal_image_stone_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstone',
            old_name='quantity',
            new_name='count',
        ),
        migrations.AddField(
            model_name='productstone',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Weight of one stone in carats', max_digits=6),
            preserve_default=False,
        ),
    ]
