# Generated by Django 5.1.4 on 2025-07-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0007_userprofile_agree_userprofile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='metal',
            name='color',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
