# Generated by Django 5.1.4 on 2025-04-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0007_delete_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='metal',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
