# Generated by Django 5.1.4 on 2025-05-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0008_rename_quantity_productstone_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
    ]
