# Generated by Django 5.1.4 on 2025-07-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0008_metal_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metal',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
