# Generated by Django 5.1.4 on 2025-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0009_product_size_alter_metal_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemstone',
            name='clarity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gemstone',
            name='shape',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
