# Generated by Django 5.1.4 on 2025-05-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0009_remove_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frozen_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
