# Generated by Django 5.1.4 on 2025-07-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0010_gemstone_clarity_gemstone_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemstone',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
