# Generated by Django 5.1.4 on 2025-04-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0010_alter_product_discount_alter_product_making_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metal',
            name='unit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metal',
            name='unit_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='discount',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='unit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='unit_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metal',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
