# Generated by Django 5.1.4 on 2025-05-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0010_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='mobile_img',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
