# Generated by Django 5.1.4 on 2025-05-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0010_product_frozen_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metal_weight',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
