# Generated by Django 5.1.4 on 2025-05-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0011_alter_product_metal_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metal_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
