# Generated by Django 5.1.4 on 2025-04-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0011_metal_unit_metal_unit_price_stone_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='karantage',
            new_name='karat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pandant_width',
            new_name='pendant_width',
        ),
        migrations.RemoveField(
            model_name='metal',
            name='price',
        ),
        migrations.RemoveField(
            model_name='metal',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='diamont_details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='general_details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stone_weight',
        ),
        migrations.RemoveField(
            model_name='stone',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stone',
            name='unit',
        ),
        migrations.AddField(
            model_name='metal',
            name='karat',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='making_discount',
            field=models.FloatField(default=0.0, help_text='Discount on making charge %'),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_weight',
            field=models.FloatField(default=1, help_text='Metal weight in grams'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_discount',
            field=models.FloatField(default=0.0, help_text='Overall discount %'),
        ),
        migrations.AddField(
            model_name='product',
            name='star_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='metal',
            name='unit_price',
            field=models.FloatField(help_text='Price per gram'),
        ),
        migrations.AlterField(
            model_name='product',
            name='grand_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gross_weight',
            field=models.FloatField(blank=True, help_text='Total weight (auto-calculated)', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gst',
            field=models.FloatField(default=3.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='making_charge',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stone_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stone',
            name='unit_price',
            field=models.FloatField(help_text='Price per carat'),
        ),
        migrations.AddField(
            model_name='metal',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jewelleryapp.material'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('weight', models.FloatField(help_text='Weight of one stone in carat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelleryapp.product')),
                ('stone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelleryapp.stone')),
            ],
        ),
    ]
