# Generated by Django 5.1.4 on 2025-05-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0011_header_mobile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='images',
            new_name='main_img',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='mobile_img',
            new_name='main_mobile_img',
        ),
        migrations.AddField(
            model_name='header',
            name='slider_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
