# Generated by Django 5.1.4 on 2025-05-20 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0012_rename_images_header_main_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stone',
            new_name='Gemstone',
        ),
    ]
