# Generated by Django 5.1.4 on 2025-04-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0012_material_rename_karantage_product_karat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metal',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
