# Generated by Django 5.1.4 on 2025-05-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0013_rename_stone_gemstone'),
    ]

    operations = [
        migrations.AddField(
            model_name='metal',
            name='purity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metal',
            name='karat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
