# Generated by Django 5.1.4 on 2025-05-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0013_alter_product_metal_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stone_count',
        ),
    ]
