# Generated by Django 5.1.4 on 2025-05-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0014_metal_purity_alter_metal_karat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metal',
            name='purity',
        ),
    ]
