# Generated by Django 5.1.4 on 2025-05-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0014_remove_product_grand_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='product',
            name='stone_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
