# Generated by Django 5.1.4 on 2025-07-07 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0015_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='jewelleryapp.category'),
        ),
    ]
