# Generated by Django 5.1.4 on 2025-05-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0015_remove_metal_purity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='karat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
