# Generated by Django 5.1.4 on 2025-04-24 10:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0015_gender_product_occasions_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
