# Generated by Django 5.1.4 on 2025-05-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0015_remove_product_subtotal_product_stone_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stone_count',
        ),
        migrations.AddField(
            model_name='product',
            name='stones',
            field=models.ManyToManyField(blank=True, related_name='products', to='jewelleryapp.stone'),
        ),
        migrations.AlterField(
            model_name='product',
            name='frozen_unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='making_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
