# Generated by Django 5.1.4 on 2025-04-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0016_gender_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stones',
            field=models.ManyToManyField(blank=True, help_text='Helper field for quick reference to stones.', related_name='products', to='jewelleryapp.stone'),
        ),
    ]
