# Generated by Django 5.1.4 on 2025-05-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0016_remove_product_stone_count_product_stones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
        ),
    ]
