# Generated by Django 5.1.4 on 2025-07-07 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0016_alter_subcategories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Subcategories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jewelleryapp.subcategories'),
        ),
    ]
