# Generated by Django 5.1.4 on 2025-07-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0017_product_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Subcategories',
        ),
        migrations.DeleteModel(
            name='Subcategories',
        ),
    ]
