# Generated by Django 5.1.4 on 2025-04-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0017_product_stones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('confirmpassword', models.CharField(max_length=128)),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
