# Generated by Django 5.1.4 on 2025-05-20 06:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0017_navbarcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbarcategory',
            old_name='handcrafted',
            new_name='is_all_jewellery',
        ),
        migrations.AddField(
            model_name='navbarcategory',
            name='all_jewellery_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='navbarcategory',
            name='is_handcrafted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='navbarcategory',
            name='handcrafted_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
