# Generated by Django 5.1.4 on 2025-04-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0019_uservisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_stone_count',
            field=models.IntegerField(blank=True, help_text='Total number of stones', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_stone_weight',
            field=models.FloatField(blank=True, help_text='Total stone weight (in carats)', null=True),
        ),
    ]
