# Generated by Django 5.1.4 on 2025-05-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0019_alter_navbarcategory_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavbarCategory',
        ),
    ]
