# Generated by Django 5.1.4 on 2025-07-25 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0020_rename_name_subcategories_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jewelleryapp.category'),
        ),
    ]
