# Generated by Django 5.1.4 on 2025-04-28 06:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0020_product_total_stone_count_product_total_stone_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stone_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total weight (auto-calculated)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='karat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='making_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='making_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Discount on making charge %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='metal_weight',
            field=models.DecimalField(decimal_places=2, help_text='Metal weight in grams', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Overall discount %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='star_rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_stone_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total stone weight (in carats)', max_digits=10, null=True),
        ),
    ]
