# Generated by Django 5.1.4 on 2025-04-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0021_remove_product_stone_price_alter_product_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='carat_weight',
            field=models.FloatField(default=1, help_text='Carat weight of the gemstone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='clarity_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stone',
            name='color_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stone',
            name='cut_grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stone',
            name='gemstone_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='unit_price',
            field=models.FloatField(help_text='Base price per carat'),
        ),
    ]
