# Generated by Django 5.2.4 on 2025-08-09 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0022_alter_product_occasion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='jewelleryapp.gender'),
        ),
    ]
