# Generated by Django 5.1.4 on 2025-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0022_navbarcategory_gemstone_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('categories', 'Categories'), ('occasions', 'Occasions'), ('price', 'Price'), ('gender', 'Gender')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.URLField()),
            ],
        ),
    ]
