# Generated by Django 5.1.4 on 2025-04-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0022_stone_carat_weight_stone_clarity_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.JSONField(default=list),
        ),
    ]
