# Generated by Django 5.2.4 on 2025-08-09 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0023_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jewelleryapp.metal'),
        ),
    ]
