# Generated by Django 5.1.4 on 2025-05-24 10:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0023_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelleryapp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to='jewelleryapp.register')),
            ],
            options={
                'ordering': ['-searched_at'],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
