# Generated by Django 5.1.4 on 2025-05-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0024_categorysearchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='uservisit',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Visit', 'verbose_name_plural': 'User Visits'},
        ),
        migrations.DeleteModel(
            name='CategorySearchHistory',
        ),
    ]
