# Generated by Django 5.1.4 on 2025-05-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0025_gif_alter_uservisit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchGif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='gifs/')),
            ],
        ),
        migrations.DeleteModel(
            name='Gif',
        ),
    ]
