# Generated by Django 5.1.4 on 2025-04-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0021_userprofile'),
        ('jewelleryapp', '0025_alter_product_images'),
    ]

    operations = [
    ]
