# Generated by Django 5.1.4 on 2025-05-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0026_searchgif_delete_gif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchgif',
            name='file',
        ),
        migrations.AddField(
            model_name='searchgif',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gifs/'),
        ),
    ]
