# Generated by Django 5.1.4 on 2025-06-03 10:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelleryapp', '0027_remove_searchgif_file_searchgif_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchgif',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
