# Generated by Django 5.2.4 on 2025-08-07 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapp', '0002_dailyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Taskapp.register'),
        ),
    ]
