# Generated by Django 5.2.4 on 2025-08-07 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskapp', '0003_dailyplan_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyplan',
            name='created_by',
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='Taskapp.register'),
            preserve_default=False,
        ),
    ]
